FROM ubuntu:latest AS prep

# Install dos2unix to convert line endings
RUN apt-get update && apt-get install -y dos2unix

# Copy the files to be converted into the prep stage
COPY ./ /docker-entrypoint-initdb.d/

# Convert line endings from Windows to Unix format
RUN find /docker-entrypoint-initdb.d/ -type f -exec dos2unix {} \;

FROM postgres:latest
COPY --from=prep /docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/