name: BudgetMate
services:
    db:
        build:
            context: ../postgresDB/init_schema
            dockerfile: dockerfile
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
            POSTGRES_DB: ${POSTGRES_DB_NAME:-BudgetMate}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        ports:
        - 8080:8080

volumes:
    pgdata:
